# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neil/code/thirdparty/uWebSockets

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neil/code/thirdparty/uWebSockets

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	cd /home/neil/code/thirdparty/uWebSockets && $(CMAKE_COMMAND) -E cmake_progress_start /home/neil/code/thirdparty/uWebSockets/CMakeFiles /home/neil/code/thirdparty/uWebSockets/uSockets/CMakeFiles/progress.marks
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f CMakeFiles/Makefile2 uSockets/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neil/code/thirdparty/uWebSockets/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f CMakeFiles/Makefile2 uSockets/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f CMakeFiles/Makefile2 uSockets/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f CMakeFiles/Makefile2 uSockets/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/neil/code/thirdparty/uWebSockets && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
uSockets/CMakeFiles/uSockets.dir/rule:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f CMakeFiles/Makefile2 uSockets/CMakeFiles/uSockets.dir/rule
.PHONY : uSockets/CMakeFiles/uSockets.dir/rule

# Convenience name for target.
uSockets: uSockets/CMakeFiles/uSockets.dir/rule

.PHONY : uSockets

# fast build rule for target.
uSockets/fast:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/build
.PHONY : uSockets/fast

src/context.o: src/context.c.o

.PHONY : src/context.o

# target to build an object file
src/context.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/context.c.o
.PHONY : src/context.c.o

src/context.i: src/context.c.i

.PHONY : src/context.i

# target to preprocess a source file
src/context.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/context.c.i
.PHONY : src/context.c.i

src/context.s: src/context.c.s

.PHONY : src/context.s

# target to generate assembly for a file
src/context.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/context.c.s
.PHONY : src/context.c.s

src/eventing/epoll_kqueue.o: src/eventing/epoll_kqueue.c.o

.PHONY : src/eventing/epoll_kqueue.o

# target to build an object file
src/eventing/epoll_kqueue.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/epoll_kqueue.c.o
.PHONY : src/eventing/epoll_kqueue.c.o

src/eventing/epoll_kqueue.i: src/eventing/epoll_kqueue.c.i

.PHONY : src/eventing/epoll_kqueue.i

# target to preprocess a source file
src/eventing/epoll_kqueue.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/epoll_kqueue.c.i
.PHONY : src/eventing/epoll_kqueue.c.i

src/eventing/epoll_kqueue.s: src/eventing/epoll_kqueue.c.s

.PHONY : src/eventing/epoll_kqueue.s

# target to generate assembly for a file
src/eventing/epoll_kqueue.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/epoll_kqueue.c.s
.PHONY : src/eventing/epoll_kqueue.c.s

src/eventing/gcd.o: src/eventing/gcd.c.o

.PHONY : src/eventing/gcd.o

# target to build an object file
src/eventing/gcd.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/gcd.c.o
.PHONY : src/eventing/gcd.c.o

src/eventing/gcd.i: src/eventing/gcd.c.i

.PHONY : src/eventing/gcd.i

# target to preprocess a source file
src/eventing/gcd.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/gcd.c.i
.PHONY : src/eventing/gcd.c.i

src/eventing/gcd.s: src/eventing/gcd.c.s

.PHONY : src/eventing/gcd.s

# target to generate assembly for a file
src/eventing/gcd.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/gcd.c.s
.PHONY : src/eventing/gcd.c.s

src/eventing/libuv.o: src/eventing/libuv.c.o

.PHONY : src/eventing/libuv.o

# target to build an object file
src/eventing/libuv.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/libuv.c.o
.PHONY : src/eventing/libuv.c.o

src/eventing/libuv.i: src/eventing/libuv.c.i

.PHONY : src/eventing/libuv.i

# target to preprocess a source file
src/eventing/libuv.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/libuv.c.i
.PHONY : src/eventing/libuv.c.i

src/eventing/libuv.s: src/eventing/libuv.c.s

.PHONY : src/eventing/libuv.s

# target to generate assembly for a file
src/eventing/libuv.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/eventing/libuv.c.s
.PHONY : src/eventing/libuv.c.s

src/loop.o: src/loop.c.o

.PHONY : src/loop.o

# target to build an object file
src/loop.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/loop.c.o
.PHONY : src/loop.c.o

src/loop.i: src/loop.c.i

.PHONY : src/loop.i

# target to preprocess a source file
src/loop.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/loop.c.i
.PHONY : src/loop.c.i

src/loop.s: src/loop.c.s

.PHONY : src/loop.s

# target to generate assembly for a file
src/loop.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/loop.c.s
.PHONY : src/loop.c.s

src/socket.o: src/socket.c.o

.PHONY : src/socket.o

# target to build an object file
src/socket.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/socket.c.o
.PHONY : src/socket.c.o

src/socket.i: src/socket.c.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/socket.c.i
.PHONY : src/socket.c.i

src/socket.s: src/socket.c.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/socket.c.s
.PHONY : src/socket.c.s

src/ssl.o: src/ssl.c.o

.PHONY : src/ssl.o

# target to build an object file
src/ssl.c.o:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/ssl.c.o
.PHONY : src/ssl.c.o

src/ssl.i: src/ssl.c.i

.PHONY : src/ssl.i

# target to preprocess a source file
src/ssl.c.i:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/ssl.c.i
.PHONY : src/ssl.c.i

src/ssl.s: src/ssl.c.s

.PHONY : src/ssl.s

# target to generate assembly for a file
src/ssl.c.s:
	cd /home/neil/code/thirdparty/uWebSockets && $(MAKE) -f uSockets/CMakeFiles/uSockets.dir/build.make uSockets/CMakeFiles/uSockets.dir/src/ssl.c.s
.PHONY : src/ssl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... uSockets"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... src/context.o"
	@echo "... src/context.i"
	@echo "... src/context.s"
	@echo "... src/eventing/epoll_kqueue.o"
	@echo "... src/eventing/epoll_kqueue.i"
	@echo "... src/eventing/epoll_kqueue.s"
	@echo "... src/eventing/gcd.o"
	@echo "... src/eventing/gcd.i"
	@echo "... src/eventing/gcd.s"
	@echo "... src/eventing/libuv.o"
	@echo "... src/eventing/libuv.i"
	@echo "... src/eventing/libuv.s"
	@echo "... src/loop.o"
	@echo "... src/loop.i"
	@echo "... src/loop.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/ssl.o"
	@echo "... src/ssl.i"
	@echo "... src/ssl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/neil/code/thirdparty/uWebSockets && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

